### PR TITLE
Clarify that edges may have overlapping calls

### LINKED ISSUE #39: crawlAsync: crashes without pooling over HTTP requests (fix or document)
Noticed in an example that this crashes when used with HTTP if the number of edges returned is more HTTP requests to be created than the VM can handle.

`crawlAsync` should either implement its own throttling/pooling or at least should document that the number of pending async operations may grow unbounded and that users should implement their own throttling/pooling

### PR DESCRIPTION
**Pull request by natebosch**
Closes #39

Add a note in the doc comment that the edges callback must be throttled
independently, it won't be throttled by `crawlAsync`.

Update the example usage to show how the `pool` package can be used to
implement limiting.

### CODE REVIEW

File: lib/src/crawl_async.dart [hunk 1]
```diff
@@ -29,6 +29,10 @@ final _empty = Future<Null>.value(null);
 /// If either [readNode] or [edges] throws the error will be forwarded
 /// through the result stream and no further nodes will be crawled, though some
 /// work may have already been started.
+///
+/// Crawling is eager, calls to [edges] may overlap with other calls that have
```
Comment (kevmoo) [inline lib/src/crawl_async.dart]: Weird sentence. Missing `so`? `Crawling is eager, so calls to`

File: example/crawl_async_example.dart [hunk 2]
```diff
@@ -11,12 +11,18 @@ import 'package:analyzer/dart/analysis/context_locator.dart';
 import 'package:analyzer/dart/ast/ast.dart';
 import 'package:graphs/graphs.dart';
 import 'package:path/path.dart' as p;
+import 'package:pool/pool.dart';
+
+/// Limits calls to [findImports].
+final _pool = Pool(10);
```
Comment (kevmoo) [inline example/crawl_async_example.dart]: Better to put this in the main function? Avoid global state? Encourage best practices...etc etc

Comment (natebosch) [reply example/crawl_async_example.dart]: Done

File: lib/src/crawl_async.dart (hunk 1 above)
Comment (natebosch) [reply lib/src/crawl_async.dart]: Done

File: example/crawl_async_example.dart (hunk 2 above)
Comment (natebosch) [reply example/crawl_async_example.dart]: Hmm, thinking more about this I'm a little more inclined to make it global. We tend to make instances of `Pool` objects global because they typically reflect limits which are global to the VM - like HTTP requests, or file handles...

I guess I don't feel strongly about it either way though - it's a contrived example so it doesn't hurt to have a contrived approach.
